////////////LIBROS/////////////////////////////
###
GET http://localhost:3000/api/libros

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/autor

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/autor_descripcion

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/name

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/descripcion

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/bundles

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/score

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/genres

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/paginas

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/fecha

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/relatedTo

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/followers

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/resena1

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/resena1_nom

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/resena1_rating

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/resena1_num


###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/resena2

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/resena2_nom

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/resena2_rating

###
GET http://localhost:3000/api/libros/64506dcb369fb837314fe2eb/resena2_num

###
POST http://localhost:3000/api/libros
Content-Type: application/json

{
        "name":"El Ultimo Héroe del Olimpo",
        "autor":"Rick Riordan",
        "autor_descripcion":"Rick Riordan es el autor de muchos libros más vendidos del New York Times, incluida la serie Percy Jackson.",
        "descripcion":"Los mestizos han dedicado mucho tiempo a prepararse para la batalla decisiva contra los titanes, aunque saben que sus posibilidades de obtener la victoria son mínimas. El ejército de Cronos es ahora más formidable que nunca y, con cada dios y cada mestizo que logra reclutar, aumentan los poderes del maligno titán. Tras fracasar en un primer intento de detener en alta mar las arrolladoras tropas de Cronos, Percy Jackson y los olímpicos se esfuerzan por mantener a raya la furia desatada del monstruo Tifón. Y cuando Cronos ordena el avance definitivo hacia Nueva York, donde el monte Olimpo, en lo alto del Empire State, se encuentra prácticamente indefenso, pararle los pies al implacable Señor del Tiempo dependerá exclusivamente de Percy y su hueste de jóvenes semidioses..",
        "score":"4.5",
        "bundle":"Percy Jackson y los Dioses del Olimpo",
        "genres": "Fantasía, Mitología Griega, Ficción, Aventura",
        "paginas":"381 páginas",
        "fecha":"Publicado el 5 de Mayo, 2009",
        "releatedTo": "La Maldición del Titán, La Batalla del Laberinto",
        "followers": "Alfonso, Javier, Shuraby",
        "resena1":"Acabo de leer el pico de la ficción.",
        "resena1_nom":"etor",
        "resena1_rating":"5",
        "resena1_num":"420",
        "resena2":"The Great Prophecy was indeed in his lifetime.",
        "resena2_nom":"Rick",
        "resena2_rating":"5",
        "resena2_num":"1"
}

###
DELETE  http://localhost:3000/api/libros/6477dbef5300581a3df28f80

###
PUT  http://localhost:3000/api/libros/6477d9fc5300581a3df28f77
Content-Type: application/json

{
        "name":"El Ladrón del Rayo",
        "autor":"Rick Riordan",
        "descripcion": "¿Qué pasaría si un día descubrieras que, en realidad, eres hijo de un dios griego que debe cumplir una misión secreta? Pues eso es lo que le sucede a Percy Jackson, que a partir de ese momento se dispone a vivir los acontecimientos más emocionantes de su vida. Expulsado de seis colegios, Percy padece dislexia y dificultades para concentrarse, o al menos ésa es la versión oficial. Objeto de burlas por inventarse historias fantásticas, ni siquiera él mismo acaba de creérselas hasta el día que los dioses del Olimpo le revelan la verdad: Percy es nada menos que un semidiós, es decir, el hijo de un dios y una mortal. Y como tal ha de descubrir quién ha robado el rayo de Zeus y así evitar que estalle una guerra entre los dioses. Para cumplir la misión contará con la ayuda de sus amigos Grover, un joven sátiro, y Annabeth, hija de Atenea.",
        "score":"4.2",
        "bundle":"Percy Jackson y los Dioses del Olimpo",
        "genres": "Fantasía, Mitología Griega, Ficción, Aventura",
        "releatedTo": "The Heroes of Olympus, The Trials of Apollo, Magnus Chase and the Gods of Asgard",
        "followers": "Alfonso, Javier, Shuraby"
        
    
}


/////////GRUPOS/////////////////////////////////
###
GET http://localhost:3000/api/grupos

###
GET http://localhost:3000/api/grupos/6450b1c20b0037a70435dc31

###
GET http://localhost:3000/api/grupos/6450b1c20b0037a70435dc31/nombre

###
GET http://localhost:3000/api/grupos/6450b1c20b0037a70435dc31/miembros

###
GET http://localhost:3000/api/grupos/6450b1c20b0037a70435dc31/descripcion

###
DELETE  http://localhost:3000/api/grupos/647c1f208711cc52f19cea45

###
POST http://localhost:3000/api/grupos
Content-Type: application/json

{
    "nombre":"Grupo Lectura CETYS",
    "miembros":"etor, Alfonso, Javier, Shuraby, Sofia",
    "descripcion":"El ganador de la votación fue Quiubole con.... Estaremos leyendo los primeros 3 capítulos para el 25 de febrero y lo estaremos platicando en la semana del 28.",
    "miembro1nom":"Alfonso",
    "miembro1post":"A simple vista un libro de instrucción con lenguaje común y, a momentos soez, en profundidad de análisis Quiúbole con... demuestra ser una obra con una capacidad formativa considerable, la cual es sin lugar a duda un catalizador para el desarrollo del pensamiento crítico en la juventud...",
    "miembro1tit":"Simplemente fenomenal",
    "miembro1lib":"Quiobole con...",
    "miembro1group":"Grupo de Lectura CETYS",
    "miembro2nom":"Javier",
    "miembro2post":"no me gusta yo leo puros libros de comunistas q es esto no le entendí",
    "miembro2tit":"No me gustó",
    "miembro2lib":"Quiobole con...",
    "miembro2group":"Grupo de Lectura CETYS",
    "miembro3nom":"Shuraby",
    "miembro3post":"I'm just here so I don't get fined",
    "miembro3tit":"Si muy padre",
    "miembro3lib":"Quiobole con...",
    "miembro3group":"Grupo de Lectura CETYS"
}

###
PUT http://localhost:3000/api/grupos/647c1f208711cc52f19cea45
Content-Type: application/json

{
    "nombre":"Grupo Lectura CETYS",
    "miembros":"etor, Alfonso, Javier, Shuraby, Sofia",
    "descripcion":"El ganador de la votación fue Quiubole con.... Estaremos leyendo los primeros 3 capítulos para el 25 de febrero y lo estaremos platicando en la semana del 28."     
}


//////////////AUTOR/////////////////////////////
###
GET http://localhost:3000/api/autores

###
GET http://localhost:3000/api/autores/6450b51c271e59d67bc881a6

###
GET http://localhost:3000/api/autores/6450b51c271e59d67bc881a6/nombre

###
GET http://localhost:3000/api/autores/6450b51c271e59d67bc881a6/about

###
GET http://localhost:3000/api/autores/6450b51c271e59d67bc881a6/libros

###
POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre":"Rick Riordan",
    "about":"Rick Riordan is the #1 New York Times bestselling author of many books, including the Percy Jackson series. You can follow him on Twitter and via his official website.",
    "libros":"Percy Jackson and the Olympians, The Heroes of Olympus, The Red Pyramid, The Trials of Apollo, Magnus Chase and the Gods of Asgard, The Sun and the Star, Percy Jackson and the Olympians: The Chalice of the Gods, Daughter of the Deep"     
}

###
PUT  http://localhost:3000/api/autores/6450b51c271e59d67bc881a6
Content-Type: application/json

{
    "nombre":"Rick Riordan",
    "about":"Rick Riordan is the #1 New York Times bestselling author of many books, including the Percy Jackson series. You can follow him on Twitter and via his official website.",
    "libros":"Percy Jackson and the Olympians, The Heroes of Olympus, The Red Pyramid, The Trials of Apollo, Magnus Chase and the Gods of Asgard, The Sun and the Star, Percy Jackson and the Olympians: The Chalice of the Gods, Daughter of the Deep, Percy Jackson and the Olympians: The Demigod Files"     
}

###
DELETE  http://localhost:3000/api/autores/6450b13f767e2781ff136c6e


////////////////////////USUARIOS///////////////////////
###
GET http://localhost:3000/api/usuarios

###
GET http://localhost:3000/api/usuarios/645182690c711733294f954c

###
GET http://localhost:3000/api/usuarios/645182690c711733294f954c/username

###
GET http://localhost:3000/api/usuarios/645182690c711733294f954c/reviews

###
GET http://localhost:3000/api/usuarios/645182690c711733294f954c/grupos

###
GET http://localhost:3000/api/usuarios/645182690c711733294f954c/friends

###
GET http://localhost:3000/api/usuarios/645182690c711733294f954c/WantToRead

###
GET http://localhost:3000/api/usuarios/645182690c711733294f954c/activity

###
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "username":"achi_02",
    "reviews":"'Yo ya me hubiera ido con la Rachel la verdad.' - Percy Jackson and the Olympians: The Battle of the Labyrinth",
    "grupos":"pppjalv",
    "friends":"Alfonso, Javier, Shuraby, Sofia",
    "WantToRead":"From the world of Percy Jackson: The Sun and the Star",
    "activity":"Actualmente leyendo: Harry Potter and the Chamber of Secrets"    
}

###
PUT http://localhost:3000/api/usuarios/645182690c711733294f954c
Content-Type: application/json

{
    "username":"achi_02",
    "reviews":"'Yo ya me hubiera ido con la Rachel la verdad.' - Percy Jackson and the Olympians: The Battle of the Labyrinth",
    "grupos":"pppjalv",
    "friends":"Alfonso, Javier, Shuraby, Sofia",
    "WantToRead":"Percy Jackson and the Olympians: The Chalice of the Gods",
    "activity":"Actualmente leyendo: Harry Potter and the Chamber of Secrets"    
}

###
DELETE http://localhost:3000/api/usuarios/64517ee81a12fc3b1633f348